### ISSUE TITLE
I can't run the project

### ISSUE THREAD

**Issue by Aladin056** [PEC-CSS/Stock-Watchlist#41]
![image](https://user-images.githubusercontent.com/60187573/157238726-2e4ae8e0-78f0-4781-987d-3793333b477e.png)

**Comment by Aladin056** [comment]
![image](https://user-images.githubusercontent.com/60187573/158156365-845fe959-8414-4bc4-be39-8cda62c6b192.png)

**Comment by Aladin056** [comment]
![image](https://user-images.githubusercontent.com/60187573/158158672-e1910085-e6fe-46ea-b426-56fa21648002.png)

**Comment by Rahul5430** [comment]
Hey @Aladin056. Try running the app using expo-dev-client.
First, run:-
```
eas build --profile development --platform android
```
Then start dev server:-
```
expo start --dev-client
```

You can also refer to expo docs:- https://docs.expo.dev/development/getting-started/.

**Comment by Sahilkumarrr13** [comment]
Issue Resolved
